opt_in_rules:
  - attributes
  - closure_spacing
  - conditional_returns_on_newline
  - empty_count
  - first_where
  - operator_usage_whitespace
  - private_outlet
  - sorted_imports

type_name:
  max_length: 60

line_length:
  ignores_urls: true
  ignores_comments: true
  ignores_interpolated_strings: true

identifier_name:
  min_length:
    error: 4
  max_length: 60
  excluded:
    - api
    - app
    - id
    - lhs
    - rhs
    - url
